name: Create Release on Version Change

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read version from config/version.json
        id: read_version
        run: |
          set -e
          VERSION=$(jq -r '.version' config/version.json)
          echo "::set-output name=VERSION::$VERSION"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.read_version.outputs.VERSION }}
          release_name: Release v${{ steps.read_version.outputs.VERSION }}
          draft: false
          prerelease: false
