name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASS }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            find . -type f -name "*.pyc" -delete
            find . -type d -name "__pycache__" -exec rm -r {} +
            git fetch --all
            git reset --hard origin/main
            source iphone3g/bin/activate
            pip install -r requirements.txt
            sudo systemctl stop iphone3g.service
            sleep 15
            sudo systemctl start iphone3g.service
