name: Deploy to Server

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASS }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            find . -type f -name "*.pyc" -delete
            find . -type d -name "__pycache__" -exec rm -r {} +
            git pull
            bash -c "source iphone3g/bin/activate && pip install -r requirements.txt"
            sudo systemctl stop iphone3g.service
            sleep 10
            sudo systemctl start iphone3g.service
