name: Enhanced Static Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black isort mypy bandit safety
    
    - name: Run Ruff linting
      run: |
        ruff check . --output-format=github
    
    - name: Check code formatting with Black
      run: |
        black --check .
    
    - name: Check import sorting with isort
      run: |
        isort --check-only .
    
    - name: Type checking with mypy
      run: |
        mypy . --ignore-missing-imports || true
    
    - name: Security analysis with Bandit
      run: |
        bandit -r . -x tests/ -f json -o bandit-report.json || true
    
    - name: Dependency vulnerability check
      run: |
        safety check --json --output safety-report.json || true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install radon complexity-report
    
    - name: Calculate code complexity
      run: |
        radon cc . --min=B --show-complexity --total-average
    
    - name: Calculate maintainability index
      run: |
        radon mi . --min=B --show --sort

  documentation-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Validate wiki links and structure
      run: |
        python scripts/validate-wiki.py
    
    - name: Check for TODO/FIXME comments
      run: |
        find . -name "*.py" -exec grep -Hn "TODO\|FIXME\|XXX\|HACK" {} \; || true
    
    - name: Verify command documentation accuracy
      run: |
        python scripts/validate-wiki.py --check-commands
